### ISSUE TITLE
Fails to Build on FreeBSD 14.3-RELEASE

### ISSUE THREAD

**Issue by tuaris** [workflow-rs/workflow-rs#15]
I'm trying to build a project that uses this library as a dependency, but it fails to detect my operating system correctly:

```
error[E0308]: mismatched types
   --> /home/daniel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/workflow-core-0.18.0/src/runtime.rs:349:25
    |
349 |           .get_or_init(|| {
    |  _________________________^
350 | |             cfg_if! {
351 | |                 if #[cfg(target_os = "windows")] {
352 | |                     Platform::Windows
...   |
369 | |         })
    | |_________^ expected `Platform`, found `()`

For more information about this error, try `rustc --explain E0308`.
warning: workflow-core@0.18.0: not within a suitable 'git' worktree!
warning: workflow-core@0.18.0: VERGEN_GIT_BRANCH set to default
warning: workflow-core@0.18.0: VERGEN_GIT_COMMIT_AUTHOR_EMAIL set to default
warning: workflow-core@0.18.0: VERGEN_GIT_COMMIT_AUTHOR_NAME set to default
warning: workflow-core@0.18.0: VERGEN_GIT_COMMIT_COUNT set to default
warning: workflow-core@0.18.0: VERGEN_GIT_COMMIT_DATE set to default
warning: workflow-core@0.18.0: VERGEN_GIT_COMMIT_MESSAGE set to default
warning: workflow-core@0.18.0: VERGEN_GIT_COMMIT_TIMESTAMP set to default
warning: workflow-core@0.18.0: VERGEN_GIT_DESCRIBE set to default
warning: workflow-core@0.18.0: VERGEN_GIT_SHA set to default
warning: workflow-core@0.18.0: VERGEN_GIT_DIRTY set to default
error: could not compile `workflow-core` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```
